### ISSUE TITLE
Use of DHCP addresses

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#101]
Hey guys, as you know, our devices have multiple VLANS, one for internet access and one for management.  In order to have the UCRM successfully connect to the client devices, I have had to start adding the IP addresses of the management interfaces.

That said, while doing this, I have had a number of issues where the UCRM tells me that the IP address is in use in the system.  This is most likely due to the DHCP address changing and it not being updated in UCRM.

So, I guess my post is a two-part post.

1 - Does the UCRM update it's address table accordingly?
2 - Can we have a link placed in the warning message, where we can actually see what device the "used" IP address is assigned to?

**Comment by UBNT-Petr** [comment]
1- So far, UCRM supports only static IPs, not DHCP. IPs are not updated automatically.
2- You can find a client by IP - go to the client list and fill in the IP into the text search field.

**Comment by Pakket** [comment]
Yeah, that's not working for me.  System says this IP is in use in a service. I search in the client's list text field for that IP and it yields nothing.

**Comment by tobyrstephens** [comment]
Pakket, I had the same problem but later found the IP associated with an archived client.    Just an idea?

**Comment by Pakket** [comment]
None of my archived clients have services associated with them. The all have the "add service" button, not no lingering services.

**Comment by UBNT-Petr** [comment]
In the current UCRM version, these issues are covered:
* when a client is archived, the service device is still attached to that client.
* you can find any client (regular or archived) by the service device IP (use the top header search field)
* when a client is restored from the archive, the service and service device are still attached to the client.
* you can detach a service device from the service and attach it again to any other service

Feel free to create a new request or question regarding these issues
