### ISSUE TITLE
Editing Client details does not change Invoice details

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#102]
There is no way of effecting client contact details on existing Invoices. Once done , client information saved on invoice remains inspite of changing on client form, and there is no edit form for this on "edit invoice".

**Comment by UBNT-Petr** [comment]
No, UCRM does not allow to change contact details on existing invoices. For now, you need to delete these invoices and create new ones, or let ucrm create them (Note that automated invoicing is applied only to services)
