### ISSUE TITLE
Client Zone - Add 'Change Service Plan'

### ISSUE THREAD

**Issue by 1WisTech1** [U-CRM/billing#111]
I'd like to see an option for a customer to change service plan for a full billing cycle.  We can set what values should be allowed based on residential/commercial accounts.  The billing system should be able to pro-rate accordingly if necessary.

**Comment by UBNT-Petr** [comment]
discussed here: https://community.ubnt.com/t5/UCRM-Feature-Requests/Client-Zone-Add-Change-Service-Plan/idi-p/1804117
