### ISSUE TITLE
[ Guide Request ] Mikrotik Routers

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#112]
Looking around on the ubnt KB and here i do not see a link on how to setup ucrm with mikrotik routers. Is there a guide somewhere i can point users to help them out with setting it up including the netflow part of it.

@vlada-dev 
@keksa 
@Jimbouse

**Comment by UBNT-Petr** [comment]
@Dstahl0 
These are currently the only available guides for Mikrotik:
1) Suspension - https://help.ubnt.com/hc/en-us/articles/220161007-UCRM-Setting-up-Network-Devices#mikrotik%20routeros
2) NetFlow - user just need to set up destination IP = UCRM servicer IP; and destination port = 2055;
3) QoS - is not implemented for Mikrotik devices

If you need some more info, please let me know.

**Comment by NahomMengistu** [comment]
Hello! 
I am having a problem also, Can you help me how to link mikrotik router to ucrm clients.
