### ISSUE TITLE
Invoices & Quotes 

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#114]
Is it possible to have a configurable terms and conditions setting for invoices (and possibly quotes in future) so that for each invoice you configure, it shows up under terms and conditions.

**Comment by arebacollins** [comment]
Any updates on this one? I am happy to come back monitor once it reaches the top of the queue. :-)

**Comment by keksa** [comment]
Hello @arebacollins, could you please ellaborate on the feature you would like? You can now specify default invoice notes for your organization which are then automatically added to every new invoice. Do you need something more?
Also could you please post your feature request here? https://community.ubnt.com/t5/UCRM-Feature-Requests/idb-p/UCRM-Ideas

**Comment by arebacollins** [comment]
Dear @keksa ,
This is specifically about Quotes, Ill do a quick highlight here and then paste verbatim at the forums. 

Workflow: 
1: Client enquires about service.
2: We do a site survey, and fill in a Quotation based on specific site. (Quote looks like invoice, only pdf generated is called Quotation) and there is a customizable dropdown with something called "Status", so an invoice is either in Draft, Sent to client, Awaiting Site Survey, Site Survey done, Negotiating, then Client Approved". 
3: Once client approves, Quote can be converted to Invoice.

It is an important document because: 
a) Graphic of invoices / sales stage of invoice / person responsible gives overview of performance of staff. Persons that close quickly are then able to be assigned more clients, and persons who just cant close are reassigned. 
b) Quotes give pipeline and pipeline by stage. 

Just this metric can give all this sales data, based on value of quote, person in charge of quote, and stage of quote.  

![sugarcrm-main-dashboard](https://cloud.githubusercontent.com/assets/1815222/22349241/e6f2e0b8-e41f-11e6-9db7-e6c48da939ff.png)

**Comment by zipcodetechnology** [comment]
+1 can we also allow a contracts to be attached to the quote for digitalsignature
