### ISSUE TITLE
Your script has a bug

### ISSUE THREAD

**Issue by truckmasterxanga** [U-CRM/billing#119]
Line 104 in the install.sh script has an error.
It currently reads as follows:
`if [ -z "$(getent passwd $UCRM_USER)" ]; then`
It should read as follows:
`if [ -z "$(getent passwd "$UCRM_USER")" ]; then`

Please resolve this as quickly as possible.

Thank you.

**Comment by keksa** [comment]
Hello @truckmasterxanga, thank you for the report. Take a look at #118, we will be merging this soon.
