### ISSUE TITLE
Higher Contrast

### ISSUE THREAD

**Issue by JimBouse** [U-CRM/billing#121]
Please add some higher contrast colors to the web UI.  I can barely see the boxes and have to blindly click around until I find them.
![image](https://cloud.githubusercontent.com/assets/3185434/22794712/c3e3235e-eeb9-11e6-973b-cb3a0773759c.png)

**Comment by arebacollins** [comment]
Im good with the way it is, Would suggest theming instead, so one can choose, or at least change css of a few elements.

**Comment by JimBouse** [comment]
Have you tried using this on a laptop in the sun?  Much work is done outdoors when running a WISP.

**Comment by Dstahl0** [comment]
+1

**Comment by keksa** [comment]
@JimBouse @arebacollins @Dstahl0 We'll take a look into this, you made a good point.

**Comment by UBNT-Petr** [comment]
Improved in 2.4.0-beta2

Even better improvements will follow in the future development including color schemes, for example.
