### ISSUE TITLE
Placeholder for billing period (mm/yy) in new Invoices email.

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#130]
Would it be possible to add customization options for the new invoices emails by adding more placeholders (and if possible a customization of these). 

For example, I would like my automatic email with invoice to read: 

Subject: Your Internet Invoice for March - April 2019.

with part of the body also having an option to indicate that the invoice is for that particular billing period. 

Is there a workaround in the meantime?

**Comment by UBNT-Petr** [comment]
Please upvote this feature request which I have created: https://community.ubnt.com/t5/UCRM-Feature-Requests/More-placeholders-for-email-notifications/idi-p/1890016

You can also specify more details there.
