### ISSUE TITLE
Upgrade from latest stable to latest beta crashes whole install

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#131]
`              Name                             Command               State                                        Ports                                       
-------------------------------------------------------------------------------------------------------------------------------------------------------------
ucrm_crm_draft_approve_app_1        make crm_draft_approve           Up      2055/udp, 443/tcp, 80/tcp, 81/tcp, 9000/tcp                                      
ucrm_crm_invoice_send_email_app_1   make crm_invoice_send_email      Up      2055/udp, 443/tcp, 80/tcp, 81/tcp, 9000/tcp                                      
ucrm_crm_netflow_app_1              make crm_netflow                 Up      0.0.0.0:2055->2055/udp, 443/tcp, 80/tcp, 81/tcp, 9000/tcp                        
ucrm_crm_ping_app_1                 make crm_ping                    Up      2055/udp, 443/tcp, 80/tcp, 81/tcp, 9000/tcp                                      
ucrm_crm_search_devices_app_1       make crm_search_devices          Up      2055/udp, 443/tcp, 80/tcp, 81/tcp, 9000/tcp                                      
ucrm_elastic_1                      /docker-entrypoint.sh elas ...   Up      9200/tcp, 9300/tcp                                                               
ucrm_postgresql_1                   docker-entrypoint.sh postgres    Up      5432/tcp                                                                         
ucrm_rabbitmq_1                     docker-entrypoint.sh rabbi ...   Up      25672/tcp, 4369/tcp, 5671/tcp, 5672/tcp                                          
ucrm_supervisord_1                  make supervisord                 Up      2055/udp, 443/tcp, 80/tcp, 81/tcp, 9000/tcp                                      
ucrm_sync_app_1                     make sync                        Up      2055/udp, 443/tcp, 80/tcp, 81/tcp, 9000/tcp                                      
ucrm_web_app_1                      make server                      Up      2055/udp, 0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp, 0.0.0.0:81->81/tcp, 9000/tcp 
Removing old UCRM images
Error response from daemon: page not found
root@debian:/home/ucrm# 
`

**Comment by UBNT-Petr** [comment]
I believe this has been discussed and fixed on the community forum. Please let us know if you are experiencing any further troubles.
