### ISSUE TITLE
payments API

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#147]
I would like to implement a class that can automatically update the system by automatically creating a payment, once it receives notification from my bank in the form of an email or a text message. All I need to do is be able to associate payment with client, so invoices are cleared in real time. 

Is there API reference on how this can be done?

**Comment by keksa** [comment]
Hello @arebacollins, API reference is available on this URL http://docs.ucrm.apiary.io/

**Comment by UBNT-Petr** [comment]
and also this example usage could help you: https://help.ubnt.com/hc/en-us/articles/115003906007-UCRM-API-Usage#example
