### ISSUE TITLE
Update from 2.2.1 to 2.2.3 deleted my admin account but not users

### ISSUE THREAD

**Issue by Stevo10189** [U-CRM/billing#156]
Not sure what to do....I cannot get into update customers

**Comment by Stevo10189** [comment]
I cant even login as the admin

**Comment by keksa** [comment]
Hello @Stevo10189, sorry for late answer. Make sure you are logging in using your admin username and not email. Logging via email was removed in 2.2.2 to prevent collisions, as clients now can have unlimited number of emails. If you want to use your email as username, you can fill it into the username field in your account setup.
If you did not change the default username, it should be "admin".
