### ISSUE TITLE
[Feature Request] Database Restore at Setup

### ISSUE THREAD

**Issue by Brailyn** [U-CRM/billing#157]
My Ubuntu server just piled... Since it was an old install, it was a good excuse to switch to Debian.

Upon fresh install of UCRM, it would be nice being able to upload a database backup right off the hop.

Any consideration to this would be appreciated.

Keep up the amazing work:)

**Comment by keksa** [comment]
Hello @Brailyn, thanks for the idea. Could you please make a post about it in https://community.ubnt.com/t5/UCRM-Feature-Requests/idb-p/UCRM-Ideas?

**Comment by Brailyn** [comment]
Posted.

**Comment by keksa** [comment]
Implemented in 2.5.0-beta1.
