### ISSUE TITLE
Logo: Image handling downsampling.

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#163]
Is there a way to keep the Logo the original resolution when creating pdf templates? I would rather even its loaded as the original image but scaled so the logo doesnt look grayed out.

**Comment by UBNT-Petr** [comment]
added to our scope

**Comment by arebacollins** [comment]
Having issues with logo, nothing displaying in invoices, and it seems it now wont show up on PDF invoices.

**Comment by keksa** [comment]
Will be possible in 2.5.
