### ISSUE TITLE
Notifications Frequency setting. 

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#168]
Is there / would it make sense for there to be an adjustable field that specifies when and how frequently notifications are sent? for instance the "please remind us if you have made this payment" type. I cant seem to control when these go out.

**Comment by UBNT-Petr** [comment]
All the notifications are triggered by another action or situation which appears once a month or so. None of the notifications should be sent to a single client excessively.

For example that notification you mentioned, is described here: 
![selection_036](https://cloud.githubusercontent.com/assets/16362380/26206245/8ff53a64-3be4-11e7-92d1-0bb7ed494f1b.png)

Additionally, as of version 2.4.0-beta1, you can turn the notifications on/off in System > Notifications > Settings
