### ISSUE TITLE
Stripe Standalone Payment Showing up in UCRM

### ISSUE THREAD

**Issue by Brailyn** [U-CRM/billing#170]
Just accepted a payment yesterday through my Stripe account web interface.

I noticed today that it is showing up as a payment from one of the users in UCRM... No correlation to that user (name, phone, address etc.). I've since detached it.

Not sure if this is a glitch, or if UCRM was intended to have a standalone Stripe account.

Don't know what details I can provide to help you understand this better. Let me know.

**Comment by UBNT-Petr** [comment]
Hi,
that payment you received was not related to UCRM at all? 

It might happen that the Stripe payer account could be on of your UCRM client, that could be the reason why it matched although the payment is not related with UCRM.

Can you please check that?

**Comment by Brailyn** [comment]
It was made in the Stripe Interface with my own Stripe account (Payments>New).

I added the payment with their credit card provided over the phone.

**Comment by keksa** [comment]
Since UCRM version 2.7.1 we add metadata to Stripe payments and if not present, ignore the payment. Should handle this case.
