### ISSUE TITLE
Logo upload issues

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#173]
Logo and stamp wont upload, old one no longer showing in invoices and documents.

**Comment by keksa** [comment]
Hello @arebacollins, please provide us with following information:
- your UCRM version
- format of the logo/stamp (i.e. jpeg, png, gif, etc.)
- file size of the images
- do you see an error after submitting the organization edit form with logo/stamp upload?
- if not, do you see the logo/stamp on organization detail page?
- can you try uploading different image files and see if it works with them?

I tried both logo and stamp upload in clean installations of 2.3.3 and 2.4.0-beta2 and both work without any problems for me.

**Comment by arebacollins** [comment]
500 Internal Server Error

An error happened.

ZGVmNTAyMDA1N2RiNjlhMjZiYzRhMWYxNGJiNzNjNGE4N2I5NmE0YzQxZGMwNzIzMzE4MzFjZTg2MWQwNjJjOTcyYmUzY2ZjYzc4NjVjMzUzYWY4NDFmODJkNjg3NTlhYjIzZjEwNjQ4ZjdmNDJhMDdkOGVlODk2NTljMjUzZDNkYWVjNDkxMmY0YmQwMDE4ZGEwN2ZlNjgzNzNkMWY0ZjFmMmZmMTJjYjJjNDRmZWZjMGNmY2FkMjQ4OWI5ZGI4NmY3NjU1ZDZmNzA5NmRmZWIyMTRhYzBiZmU5YjNkZjc5MDhmNzI1MjI4ZWI4OWExMmQ5ODk1OWMyZTM0NjliNmE2MzBhZTI1MzQxOTZjMTI4ZTcwNTVmYmY1YzlmMTIzZjBlYmZjNGIzYTU2NmIwM2Y0OGYzNmZkYmNjNGZlNTlkNDg2OWQyMTIyZjdkMTE3ZmVhZTljMzAwZjM5ZWQ3NzNhZjdiZGMxOGI5YWFjYjg1YTk3OWRiM2VhNTZlYTkzM2I1YjVlZjJmZjUxNWQxODc1OTUxZTk2Mjg1OTkzMDcyYThiYzJjMzU4OGZmZDA3ZTUwYmM4ZWVkZDQ5YmQ3YmRiNGY0ZDZjY2VmMTgyMjEyY2U5OGYyZmFjYzc1OWY2YzNkNDBkOGY5OGU2ZmVmZTZkNDNmZjUyNmZjNjZlMmEyZmNiMDZhZWEwNDYyMmZkZWJiMTE2ZTc2M2ViNjRlNDdlMzg4Mzc1YmJiNzdmN2UxMzYwYjgyOTczZDU2ZTU2MTgzMzExN2EwNzczYzI3NzQ1NzZkZDJjODk5MjEyNThlZDNjNWU5ZWY0MGI3M2JlMmY0ZWI4MzZjZDI0NjMyYmFmZWU1ZjNmY2ZkN2MxMTM2NmY2ZjFkYTg1NjNhYjg2ZGI1Njk4OGMzOWY1YWQ1NjFlMDVmNjBiOWM1MTZmOGNmMjRhZWE2NzEyYTIwMzgxYWEyOWUwODhhZDViZWIzYmE4NmY5OTk1ZmZmNjQxYTM5NGUwMjc0YWNhYTdjZWYxMThkNDJhNGM2YmZlMjBmYTY3MzI1N2Q2Y2I0Mjc2ZTYxZDcy

**Comment by arebacollins** [comment]
Hello @arebacollins, please provide us with following information:

////your UCRM version
was initially 2.3.3 but I have tried 2.4.0 as well, same result. 
//////format of the logo/stamp (i.e. jpeg, png, gif, etc.)
.png, .jpg, same error again.  (Could it be a permission issue? which folder does ucrm store images so I just upload the file and see if its just the upload process? 
////////file size of the images
248kb, 198kb, 10kb (jpeg) 
////// do you see an error after submitting the organization edit form with logo/stamp upload?
Yes. as Pasted above.
///// if not, do you see the logo/stamp on organization detail page?
N/A, No logo
//// can you try uploading different image files and see if it works with them?
Tried, not working
I tried both logo and stamp upload in clean installations of 2.3.3 and 2.4.0-beta2 and both work without any problems for me.

If its any help, Ubuntu, Linode with little in the form of resource (memory & CPU utilization.

**Comment by keksa** [comment]
@arebacollins Ok, so the error message says `Unable to create the "/usr/src/ucrm/app/../web//uploads/logo/" directory`. The problem seems to be in the double slash `/` character in path.
I have no idea how that happened in your instance, as it generates path for me with only single slash. However I added a check for this to the upload code, so it should be fixed in next release.

**Comment by arebacollins** [comment]
I backed up, reinstalled and its now ok.
