### ISSUE TITLE
Device discovery as opposed to manual entry

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#18]
Why can we not simply discover devices on a particular subnet (much like UCRM Control) instead of having to add each device manually?

Also, is the intention of UBNT to replace or merge UCRM Control into UCRM Billing?

**Comment by UBNT-Petr** [comment]
Device discovering is one of the features included in our scope. Some of the UCRM Control features will be surely integrated into UCRM Billing such as other control features which are inseparable from billing.

**Comment by Dstahl0** [comment]
Whats the status on this @UBNT-Petr ?

**Comment by UBNT-Petr** [comment]
@Dstahl0 please refer to the [UCRM roadmap](http://community.ubnt.com/t5/UCRM-Complete-WISP-Management/UCRM-Roadmap/m-p/1623895#U1623895)
We have a lot of control features planned for this summer and they are really a must for billing. So the device discovery will be probably added later.

**Comment by UBNT-Petr** [comment]
Device discovery will be incorporated through the integration with UNMS tool. Read more here: https://community.ubnt.com/t5/UCRM-Complete-WISP-Management/UCRM-integration-with-UNMS/m-p/1919207#U1919207
