### ISSUE TITLE
 mapping values are not allowed here

### ISSUE THREAD

**Issue by sgaits** [U-CRM/billing#2]
sudo docker-compose up -d
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 7, column 19

Ubuntu 15.10

**Comment by keksa** [comment]
In the forum topic it was determined this error is due to using html version of compose file. Please make sure you download raw text. Links for that were added to readme.

**Comment by sgaits** [comment]
Thank you for updating the link to the two files.  WGET with the link address now downloads the actual file.
ISSUE CLOSED
