### ISSUE TITLE
Device IP range outside of AP

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#20]
When adding a device in the client service, it warns me that the device is outside of the IP range of the AP.

Our APs only have an address assigned to them on their management interface, the VLANs that provide internet service to the CPE devices are simply bridged in the AP, so naturally, the CPE devices are going to be on a separate VLAN than our core network APs.

Since the APs and the CPE radios work on layer 2 (as far as connectivity is concerned), I don't see why the IP address is even an issue here.

This entire system seems to be flawed from the foundation, up.  It appears that you are forcing a single network setup type, where the ENTIRE system is on one big subnet, with no segmentation or security in mind, which simply will not work for us.

![billingdevice](https://cloud.githubusercontent.com/assets/19694329/15863372/bf15d1a4-2ca0-11e6-8050-dfd8ae9e6a04.PNG)

**Comment by UBNT-Petr** [comment]
We will remove this validation to enable the network architecture as you are using.

**Comment by Pakket** [comment]
Awesome news!

**Comment by keksa** [comment]
removed in 2.0.7
