### ISSUE TITLE
Traffic Shaping needs to be done on the CPE radio

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#21]
Traffic shaping needs to be controlled on the CPE radio instead of the AP or the router.

Bandwidth is a commodity, not just at the hand-off interface of our router to the internet provider, but within our own network as well.  If you shape the traffic at the CPE point, we save bandwidth that is on our CORE network.  Plus, in doing this, you can create a billing portal that is able to accommodate multiple network types and schematics.

As it stands now, I would have to re-configure my entire system to make it work with what is offered now in the billing system (which is not secure and offers no support of segmented subnets).  It appears that the developers are creating this system for a network that is running entirely in the same subnet, with routers, APs, switches, Backhauls all thrown together with CPE radios and routers.

Please take in consideration: Security, Bandwidth and multiple VLANs while developing this software.

**Comment by UBNT-Petr** [comment]
So far, UCRM doesn't comprise traffic shaping. It is to be implemented in future releases though. In our scope we want to cover these use-cases:

- As a WISP you can choose which device you want to use to manage the shaping: your network routers or CPEs devices
- In addition, in each device settings you will be able to A) define the shaping or B) override the shaping settings with another device settings

Is that what will be aligned with your needs?

**Comment by Pakket** [comment]
Absolutely!
Well done!

**Comment by 1WisTech1** [comment]
Petr - It'd be nice to be able to shape destination (to CPE) at the edge, and shape source (from CPE) at the radio, or a combination.  I'd like to queue download/upload separately, but have found CPE egress shaping to really be effective while using an FQ_CODEL leaf towards the CPE.

**Comment by Pakket** [comment]
I found it better to use egress on both interfaces of the CPE radio.
LAN0 - Egress = Download speed
WAN0 - Egress = Upload speed

Ingress does not work as well with traffic shaping.

**Comment by 1WisTech1** [comment]
Agreed, we find it better to limit egress out the interface at the edge facing the customer instead of traversing the wireless network, and egress out WLAN0 at the CPE, but still have a queue set up for SFQ/FQ_CODEL.

**Comment by XtriNet** [comment]
I would love to see traffic shaping from UCRM and have  mikrotik manage it

**Comment by vitaprimo** [comment]
What about integration with UniFi so traffic shaping takes place at a select UniFi SSID, so if the clients if, say, a commercial client fails to pay or has bandwidth limitations, public hotspots keep working still. Better yet, scratch UCRM for AirMax altogether and have **UCRM for UniFi**.

**Comment by UBNT-Petr** [comment]
In the current version of UCRM, traffic shaping can be enabled on CPE (airOS device) or on your router (EdgeOs device). Regarding the shaping on airOS, you can also choose if you want to use egress-only shaping or egress+igress shaping, details: http://ucrm-demo.ubnt.com/help/qos

@vitaprimo UniFi will be also included thanks to the planned integration with UNMS tool, read more here: https://community.ubnt.com/t5/UCRM-Complete-WISP-Management/UCRM-integration-with-UNMS/m-p/1919207#U1919207

**Comment by Jazziwatson** [comment]
hi, 
I have done traffic shaping on customer device CPE, but it is not working on it, as per on removing traffic shaping , full bandwidth is consuming on customer end.
but on the other hand, when traffic shaping is applicable on it, its working.
![Capture2](https://user-images.githubusercontent.com/24646540/95013203-2f933f80-0658-11eb-9c26-d15a30e39fb1.PNG)
![Capture3](https://user-images.githubusercontent.com/24646540/95013204-30c46c80-0658-11eb-849f-fc884f010f3e.PNG)
