### ISSUE TITLE
Cannot Save invoice

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#22]
Saving the invoice generates a Server error...

![billing-1](https://cloud.githubusercontent.com/assets/19694329/15870806/9235e7e0-2cbf-11e6-9f0e-455060bc4dbe.PNG)
![billing-2](https://cloud.githubusercontent.com/assets/19694329/15870805/9226cd00-2cbf-11e6-9f75-58d05b919f53.PNG)

**Comment by UBNT-Petr** [comment]
Could you please send us the string message displayed below the title "An error happened". It will help us to look into the problem more quickly. Thanks

**Comment by Pakket** [comment]
VGhlIGV4aXQgc3RhdHVzIGNvZGUgJzEnIHNheXMgc29tZXRoaW5nIHdlbnQgd3Jvbmc6CnN0ZGVycjogImxpYkVHTCB3YXJuaW5nOiBEUkkyOiBmYWlsZWQgdG8gb3BlbiBzd3Jhc3QgKHNlYXJjaCBwYXRocyAvdXNyL2xpYi94b3JnL21vZHVsZXMvZHJpKQpsaWJFR0wgd2FybmluZzogRFJJMjogZmFpbGVkIHRvIG9wZW4gc3dyYXN0IChzZWFyY2ggcGF0aHMgL3Vzci9saWIveG9yZy9tb2R1bGVzL2RyaSkKTG9hZGluZyBwYWdlICgxLzIpCls+ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBdIDAlDVs9PT09PT0+ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBdIDEwJQ1bPT09PT09PT09PT09PT09PT09PT09PT09PiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgXSA0MSUNWz09PT09PT09PT09PT09PT09PT09PT09PT09PiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF0gNDQlDVs9PT09PT09PT09PT09PT09PT09PT09PT09PT0+ICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBdIDQ2JQ1bPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09XSAxMDAlDVByaW50aW5nIHBhZ2VzICgyLzIpICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKWz4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIF0gDURvbmUgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIApFeGl0IHdpdGggY29kZSAxIGR1ZSB0byBuZXR3b3JrIGVycm9yOiBJbnRlcm5hbFNlcnZlckVycm9yCiIKc3Rkb3V0OiAiIgpjb21tYW5kOiBleHBvcnQgRElTUExBWT0iOjAiICYmIC91c3IvYmluL3draHRtbHRvcGRmIC0tbG93cXVhbGl0eSAtLWRpc2FibGUtamF2YXNjcmlwdCAnL3RtcC9rbnBfc25hcHB5NTc1OTZkODg5NTQ0MjMuMzIxNDEzNDUuaHRtbCcgJy90bXAva25wX3NuYXBweTU3NTk2ZDg4OTU1NTUzLjg5MzU1MTI1LnBkZicu

**Comment by keksa** [comment]
Hi @Pakket, could you please try again and send us error logs after this message is displayed?
Error logs are located in the data directory under the logs folder, if you don't want to post the logs here, please send it to me via private message on the UBNT forums (id UBNT-Ondra). Thank you.

It looks like there is an error happening in the end of invoice PDF generating, but there is not enough data for me to debug this. Also could you try to generate PDF export in the Billing -> Invoices section and see if that works?

**Comment by Pakket** [comment]
I have no such directory ..
![billing-folder](https://cloud.githubusercontent.com/assets/19694329/16016171/85e65b26-3167-11e6-86e8-78abb3188909.PNG)

**Comment by keksa** [comment]
Could you please send content of docker-compose.yml?

**Comment by keksa** [comment]
See #30
