### ISSUE TITLE
Ports and how they're used

### ISSUE THREAD

**Issue by 1WisTech1** [U-CRM/billing#25]
Can we get a list published of ports that are/will be used by U CRM Billing, and their corresponding service/function?

**Comment by andreas4all** [comment]
All published port you can find in your docker-compose.yml or [here](https://github.com/U-CRM/billing/blob/master/docker-compose.yml).

Default:
8080 - web app (in instalation can change to 80)
8081 - suspend page (in instalation can change to 81)

**Comment by 1WisTech1** [comment]
I did see this, but I also saw on the suspend page where you could override the suspend (as a customer) and it would redirect you to port 81, although it was set up to use 8080/8081, which is why I was asking. =)

**Comment by andreas4all** [comment]
In next release you will be able to provide port for suspend page in web app.

**Comment by 1WisTech1** [comment]
That is great news.  Thanks!

**Comment by keksa** [comment]
Done in 2.0.7
