### ISSUE TITLE
Setting Invoice day has no affect on invoice creation date

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#28]
No matter what I set the "invoice day" to in the client's information, the next invoice creation date for services is always the 1st of the next month.

**Comment by keksa** [comment]
Hello @Pakket, the "invoice day" setting is to tell the UCRM when to generate new recurring invoices. Services are always invoiced with full month periods with exception of the first or last invoice of client.

So for example if "invoice day" is set to 20, invoice drafts will be generated only after the 20th of month with due date set to 20th plus the invoice maturity days.

**Comment by Pakket** [comment]
You explained how it's SUPPOSED to work.... however, no matter what date I set it to, the next invoice date is always the 1st day of the following month.

Are you also saying that we are FORCED to send bills on the 1st of each month? If so, a client that was connected on say the 28th would receive a bill in two or three days that is pro-rated?  If not, then I am reporting a bug, in that the auto-generated date is incorrect.

**Comment by Pakket** [comment]
I don't understand why this is so hard.. In Quickbooks and also in AirCRM Billing, you simply set the date that the invoices are to start.  I fail to see why things have to be so complicated... however, I still stand by my report that this is a bug.

**Comment by keksa** [comment]
Yes, if a client was connected on 28th, than the service item on invoice would be pro-rated and invoiced from 28th to 30th of june (if it would be this month). If your invoicing period type is set to backwards and the "invoicing day" is set to say 10th, than the invoice draft would be generated on the 10th of july and the service item would have pro-rated quantity to corespond with this.

However you are right that this is confusing, so I am marking this as a bug and we will look into it more to make it easy for users.

**Comment by Pakket** [comment]
Please do so ... We would rather not get into pro-rating.  Once you do that, customers expect you to be able to pro-rate for down-time, etc.  Also, if the system is pro-rating, that means that bills for months less than 31 days would be for a lesser amount.  We may as well be billing day-by-day.

I am always up for change and I can see where the initial pro-rating would be beneficial and may actually like that better... as long as the system ONLY does it that one time.

**Comment by keksa** [comment]
The system only does pro-rating for the first invoice when service is started and for the last invoice when service is ended (if it's ended in the middle of month).

Otherwise if the invoice is from the first to the last of month, the item quantity is set to 1 (this applies to the larger periods as well). Because of this there are the dates for service items instead of quantity in invoice adding.

**Comment by Pakket** [comment]
Let me toss a monkey wrench in the issue...
What happens when we add all of our current customers to the billing system, that are already on an invoice and payment schedule?  Looks that as of of now, we will have to field a ton of calls from confused subscribers that are going to receive partial bills.

**Comment by Pakket** [comment]
Ok .. so I added another client to the system from a new install today.  After setting up the service registration date as today, the system says the next bill will be generated on 8/1/2016, instead of 7/1/2016.

So, this client would go one month and 10 days before seeing a bill.  Something is indeed wrong here.

![capture3](https://cloud.githubusercontent.com/assets/19694329/16243311/a322abe6-37c4-11e6-8195-384a7791bfcf.PNG)

**Comment by keksa** [comment]
You are correct. You can create invoice manually for the smaller period in the billing section, but it would be generated automatically on 8/1 for 6/21 - 7/31.

We will be looking into this and either provide something in settings for this, or add some warning. Furthermore we will be implementing pro-rating free solution in the future, so you will be able to keep your current payment schedule.

**Comment by thepagan** [comment]
I just wanted to add this to the thread, although I can make a fresh one if need be....

No matter what date you set as the "active from" date, the current date is saved.  You have to manually edit the active from date in the client's service page and then the invoiced from date doesn't change and there is no way to change the invoiced from date at all.  I'm assuming this is related to the current discussion.

**Comment by keksa** [comment]
Hi @thepagan, thank you for the report. The "active from" is fixed for 2.0.7 and you will be able to change the "invoicing from" if there are no invoices for service you are editting.

I'll take a look at the date difference though.

**Comment by keksa** [comment]
@thepagan so I found 2 bugs with this. First was problem with parsing the date from datepicker, thus using incorrect dates. Second was problem with javascript timezones, as it took the date saved on server correctly but moved it around to correspond to your browser timezone. Both are now fixed and will be in new release.

**Comment by thepagan** [comment]
The dates are now saving and populating properly, but there is no change to setting the invoice day.  When I set a client up for an invoice day of the 15th, the system prorates the monthly price instead of invoicing each month on the 15th.  Any update on when this will change?

**Comment by keksa** [comment]
@thepagan Yes, only the date saving/populating was fixed. We are planning to introduce solution without prorating, but I do not have an estimate for that yet.

**Comment by keksa** [comment]
fixed in 2.0.11
