### ISSUE TITLE
Password reset for users not working

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#29]
When the user is taken to the reset page from the email link, there is an error that says "This value should not be blank" after entering the new password and clicking the button.

**Comment by keksa** [comment]
Thank you for the report, this will be fixed in next release.

**Comment by Pakket** [comment]
Any idea when that may be?

**Comment by UBNT-Petr** [comment]
We will come up with the version 2.0.7 this week.

**Comment by keksa** [comment]
fixed in 2.0.7
