### ISSUE TITLE
Add the use of google apps alias addresses in the "sender Address" 

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#31]
With Google Apps (Gmail) you have to format the SMTP fields correctly, in order to make use of the alias addresses for the sender.

As it stands, we would need to create another user in our Google Apps account names:  billing@pakketcomm.com, in order for that to show up as the sender's address when a client receives and invoice.  This would cost us another license seat.

An alternative is to set up an alias under a current account, which costs us nothing.  However, unless formatted correctly, the sender will show as the primary address for that account no matter what you place in the "Sender's address" field of the system settings.

According to Google, you need the following headers to achieve this:
from:otheraddress@domain.com, sender:username@gmail.com

**Comment by keksa** [comment]
In 2.0.7 the sender address will be used correctly with sender SMTP header, as of now it is only used as "from" field with admin only emails and anything that goes to clients uses the organization email.

In 2.0.7 it will work the same way, but always using sender address correctly.

**Comment by keksa** [comment]
should be working correctly in 2.0.7, can you please try @Pakket?
