### ISSUE TITLE
Emailed Invoice shows company Bank account info and Tax ID NEEDS TO BE REMOVED

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#32]
Hey guys,
I finally got the invoices saving correctly!  My 1st test invoice came in via email and for some reason, Our company's Tax ID AND  Bank account number with routing number is printed on the invoice.  I can't think of any reason for this to be done that way.  Can you please remove the Company bank info and tax ID from the invoices?

![capture6](https://cloud.githubusercontent.com/assets/19694329/16312524/209b1610-3943-11e6-96c5-4779091766fe.PNG)

Thank you!

**Comment by keksa** [comment]
Hi @Pakket, could you please give me some background as to why this cannot be on the invoice? It's common where I live, that invoices contain the Tax ID and banking information. It's no problem to make this configurable, I would just like to know your reasons. :)

**Comment by Pakket** [comment]
Wire transfers are not widely used here in the US.  I am 38 years old and I cannot ever remember seeing this type of info on invoices.  For me to have to give you a reason.. is like you asking me "Why do Americans NOT use the metric system".  I cannot give you a valid reason as to why, only the fact that is is not used here.

What I can tell you is; checking account fraud is rampant here, and providing people with account numbers and routing numbers is an open invitation to have fraudulent checks created and cashed.  For that reason alone, I would rather keep that info off the invoices.

As far as the Tax ID, it is simply not necessary here.  Internet services are not taxable here (yet) therefore cannot be written off or exempted, so there is no reason to track Fed Tax IDs .

**Comment by keksa** [comment]
configurable in 2.0.7 - defaults to NOT include
