### ISSUE TITLE
Standard #9 envelope formatting for invoices

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#33]
Hey guys, the invoices could use some tweaking as far as font size and Logo positioning.
Using a standard #9 envelope, and folding it correctly, the return address  and recipient are not in the correct position, The font could be one step larger and the Logo stamp would look so much better if it was to the left of the return address.  This way the company logo would show up through the window.

![capture7](https://cloud.githubusercontent.com/assets/19694329/16313868/23ba4586-3949-11e6-81a9-359eaa285184.PNG)

![envelope](https://cloud.githubusercontent.com/assets/19694329/16314222/dcf788e6-394a-11e6-9dea-6a2d7407ad13.PNG)

**Comment by keksa** [comment]
We are planning more invoice templates and some customization in the future. Marking this as enhancement and we'll look into it.

**Comment by keksa** [comment]
should be better in 2.0.7, can you give it a try?

**Comment by Pakket** [comment]
Nope .. way off for a standard envelope.

**Comment by keksa** [comment]
Hm, I printed this envelope no.9 template http://www.windowenvelopes.com/v/vspfiles/downloadables/Template_13050.pdf and printed the invoice on US Letter and it looked just fine. What are you printer settings?

**Comment by Pakket** [comment]
Printer setting are nothing out of the ordinary..  Our invoices from Quickbooks fit perfectly.

![envelope1](https://cloud.githubusercontent.com/assets/19694329/16660496/88600c70-443c-11e6-88df-cdfe8c612311.PNG)

**Comment by keksa** [comment]
I tried the quickbooks PDF invoice and it looks it fits rather nicely to ours, so either there are some printer settings that you need to correct, or there is some problem with PDF generator in your installation.

Can you please verify the no.9 template link I posted earlier is correct and provide us with measurements of envelope you are using?

![invoices](https://cloud.githubusercontent.com/assets/7985651/16766403/34e61d3a-483a-11e6-89b2-4bf3c10da7a7.jpg)

**Comment by Pakket** [comment]
The template matches up with the envelope perfectly.  Here is a shot from our Quickbooks (from our sister company) invoice and a fresh invoice printed from UCRM.  There are no obscure printer settings, all factory default.  Also, both invoices were printed from Google Chrome, as we use Quickboks Online.

![sgaits_invoice](https://cloud.githubusercontent.com/assets/19694329/16769119/437bc202-4815-11e6-9a9a-cb599e12b3ed.jpg)

![ucrm invoice](https://cloud.githubusercontent.com/assets/19694329/16769126/4a27551c-4815-11e6-806a-adce678d3874.jpg)

**Comment by keksa** [comment]
Could you please try attached pdf? I found out we hadn't specified PDF page size format, this one should be correct, but I would like to be sure.

[dummy_invoice_letter.pdf.zip](https://github.com/U-CRM/billing/files/359573/dummy_invoice_letter.pdf.zip)

**Comment by keksa** [comment]
Looks like the size should now correctly correspond with what you have, so if you confirm this I can than finally adjust it. :)

**Comment by Pakket** [comment]
Here is the test file.  Looks good

![20160712_105129](https://cloud.githubusercontent.com/assets/19694329/16771712/7fc6266c-481f-11e6-9cc8-a352f959d40b.jpg)

**Comment by keksa** [comment]
Thanks @Pakket, could you give it one more try with this file? It should fit nicely now.

[dummy_second_letter.pdf.zip](https://github.com/U-CRM/billing/files/361370/dummy_second_letter.pdf.zip)

**Comment by Pakket** [comment]
Looks good!
Great job!

![20160713_093929](https://cloud.githubusercontent.com/assets/19694329/16805372/e2b29260-48dd-11e6-82b8-bdbf9cd2d551.jpg)

**Comment by UBNT-Petr** [comment]
resolved in 2.0.8 
You can set you PDF page size in Settings > System > Application
