### ISSUE TITLE
Service setup | Device connection question.

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#39]
As I stated before in an earlier post, our Access points are on a different VLAN than the CPE radios and CPE routers.  We do this to block access to the core network from the CPE so snooping customers cannot wreak havoc on our core infrastructure.

That said, when we are setting up a service, and are prompted to select the interface that they are connected to, if we choose the Access Point, the system gives an error saying that the CPE device's IP is out of range.  This is due to the AP being on a different subnet.

The only way I can get this NOT to throw an error is to select the VLAN interface of our EdgeMax router, in which the CPE devices belong.

Is this going to work? or do I need to wait until you can make the system work regardless of the Subnet that the CPE equipment is on?

I have made another logical layout graphic that hopefully better explains our network.

![pakket_logical](https://cloud.githubusercontent.com/assets/19694329/16589319/97265b58-42a0-11e6-844b-407f4a62524c.png)

**Comment by Pakket** [comment]
Update, I have tried this multiple ways and cannot get the system to successfully suspend the service.  The latest attempt was selecting the VLAN-12 interface of the router as the "conned to" device and the AirRouter's IP address and MAC address, as reflected in the VLAN-12 DHCP pool.

I kept the EdgeMax (Core Router) interface open when I clicked the "suspend Service" button.  The web interface refreshed about 5 seconds after that, telling me that the configuration had been changed.

So .. .the UCRM is making some sort of change in my EdgeMax router, however services for that CPE device are not suspended.

**Comment by Pakket** [comment]
One more thing... where in the EdgeMax router can I view the changes that the UCRM is making?  I have checked the firewall policies, QoS, config tree traffic policy... I cannot find anything.

**Comment by UBNT-Petr** [comment]
@Pakket What UCRM version are you running now? The error checking the client IP vs. router interface IP range has been already resolved since v2.0.7

Don't forget that within Edge routers only the list of blocked ips (called BLOCKED_USERS) is set by UCRM app. The current implementation does not comprise setting of Firewall/Nat rules which must be handled manually. See this guide https://help.ubnt.com/hc/en-us/articles/220161007-UCRM-Billing-Setting-up-Network-Devices

You can also check the BLOCKED_USERS list in the EdgeRoute itself:
![screenshot_17](https://cloud.githubusercontent.com/assets/16362380/16659702/90baed16-446b-11e6-8cc1-43959e3252ad.png)

**Comment by Pakket** [comment]
I am using  v1.7.0  that is probably the issue

**Comment by UBNT-Petr** [comment]
Did the upgrade to the latest version help you?

**Comment by Pakket** [comment]
Yes, it sure did... sorry for not updating the thread.
Also, can you point me in the right direction as to getting the redirect up and working?  I am not sure how to set this up in my EdgeRouter.  The suspend works flawlessly.

**Comment by UBNT-Petr** [comment]
To make the redirect to suspend page work, you have to set up the destination NAT rule on your router. Have you read this? https://help.ubnt.com/hc/en-us/articles/220161007-UCRM-Billing-Setting-up-Network-Devices#ubiquiti%20edgeos - section 2. NAT rule
