### ISSUE TITLE
Import of data from AirCRM Billing only populates the user fields

### ISSUE THREAD

**Issue by sgaits** [U-CRM/billing#4]
Importing the backup file from our AirCRM Billing accounts only pulls in the customer data.  I am missing all of my invoice history, invoices, items, plans (tariffs), etc..

**Comment by PhillipCotton** [comment]
Yes I thought it was worked out were we could import our customers and data  without a hitch! is there someone working on this issue? I am thinking of moving everything over to quick books! it would be nice to use all the automated functions. if there is some one i could talk with that would be great!

Thank You!
Phillip Cotton
Net1 Connect LLC
Moody TX 76557
254-624-8329
cottonphillip@gmail.com


PS Time is running out i have a company to run i spent time inputting all my customers and data configurations ect.....why should i have to do it again! I would have rather paid you  a yearly fee to keep things the way they are its works!

**Comment by Pakket** [comment]
We are in the same boat.  As it stands, after September,  we aren't going to be able to reference past data.  This is totally unacceptable.   Even though we are active in the beta for the new billing system, I am reluctant to use it in production due to the track record of their software.  I would like to see a LTS agreement that this will be actively supported before we do all this over again and wind up loosing after 1 year or whatever. 

If they can't do that, I have no intrest in moving forward.

**Comment by PhillipCotton** [comment]
Thank you for your input i belive i will be moving to quick books it has
reoccurring billing plus I found out for every transaction with Stripes its
cost me $2.50 per transaction at my bank it's $0.15 per transaction that's
a lot of money a year. What I don't like about the software that is the
ucrm that they don't give you a choice of merchant of your choice. The only
reason I used it it's for the functionality of it and it's funny I don't
even use all those functions. I manage everything but my computer the
old-fashioned way! I log onto each device individually if need be I tried
the automated thing and it never seem to work  very well , where it would
shut off the customer if they didn't pay. well that's what accountings job
is keeping up with the customers so i will save 28.20 per year per customer
so with over 400 customers thats quit a savings thats 11,000. A year give
or take vs 720 a year for the same amount of customers. Well the choice is
simple $11,000 will buy a lot of stuff LOL
Anyway thank you for your time it was all interesting I really love the
concept but it's just not going to work for me.

Thank you
Phillip Cotton
Net1 Connect LLC
Moody TX 76557
254-624-8329

**Comment by UBNT-Petr** [comment]
@PhillipCotton Now, UCRM incorporates several online payment processors and even more are in our scope along with another integrations with accounting tools such as Quick Books. Feel free to create or upvote a feature request here: https://community.ubnt.com/t5/UCRM-Feature-Requests/idb-p/UCRM-Ideas
