### ISSUE TITLE
SSL Certificate location

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#42]
Need a way to insert an SSL certificate, either within the system, script or guide as to how to get it on the server and in a place that it can be called or referenced.

**Comment by Pakket** [comment]
To add ... EV SSL certs are on sale @ GoDaddy.  So, the sooner we can get this done, the better.  i hate to miss out on sales !   =)

**Comment by Pakket** [comment]
Guys, if anything, could you give us instruction on how to place the SSL cert file in the right place, using Docker?

**Comment by Pakket** [comment]
I noticed that this was added to a pull request.  While we are at it, it would just be the bee's knees if we could go to system config and have a place to "Upload" the two .crt files. Instead of having to do it via CLI.

**Comment by UBNT-Petr** [comment]
working on it

**Comment by keksa** [comment]
2.0.8 will have certificate upload form and correct SSL support

**Comment by Pakket** [comment]
WOO HOO !

**Comment by Dstahl0** [comment]
W00t!

**Comment by UBNT-Petr** [comment]
resolved in 2.0.8. You can follow this guide: https://github.com/U-CRM/billing/wiki/SSL-certificate-guide
