### ISSUE TITLE
installation U-CRM/billing

### ISSUE THREAD

**Issue by mdsarr** [U-CRM/billing#45]
hi,
i try to install u-crm/billing on my debian jessie 64bits.
After running following commands : 
su root
apt-get update
apt-get install curl -y
**curl -fsSL https://raw.githubusercontent.com/U-CRM/billing/master/install.sh | sh**
my shell stay on this line : 
Replacing path in docker compose
Replacing env in docker compose
and i can't access to http://localhost to see my new **U-crm** billing installation.
I ask what is the next step to run or start u-crm billing on my host.
Thanks

**Comment by thepagan** [comment]
when you run this command:

`curl -fsSL https://raw.githubusercontent.com/U-CRM/billing/master/install.sh | **sudo** sh`

be sure you have the sudo before the sh.

**Comment by mdsarr** [comment]
on **su root** mode, you don't need sudo before the sh

**Comment by mdsarr** [comment]
thanks for your help i add sudo before sh and it's work and start packages download .
Thank you for your help

**Comment by mdsarr** [comment]
i have finish installation of u-crm
`---------
ucrm_crm_draft_approve_app_1        make crm_draft_approve           Up      80/tcp, 81/tcp, 9000/tcp                             
ucrm_crm_invoice_send_email_app_1   make crm_invoice_send_email      Up      80/tcp, 81/tcp, 9000/tcp                             
ucrm_elastic_1                      /docker-entrypoint.sh elas ...   Up      9200/tcp, 9300/tcp                                   
ucrm_postgresql_1                   /docker-entrypoint.sh postgres   Up      5432/tcp                                             
ucrm_sync_app_1                     make sync                        Up      80/tcp, 81/tcp, 9000/tcp                             
ucrm_web_app_1                      make server                      Up      0.0.0.0:8080->80/tcp, 0.0.0.0:8081->81/tcp, 9000/tcp `
now i need to access on the web page:
http://localhost display anything.
thanks for your help

**Comment by Pakket** [comment]
http://localhost:8080

**Comment by UBNT-Petr** [comment]
We have also updated the installation command which will handle this situation: 
https://github.com/U-CRM/billing/wiki/Installation-guide
