### ISSUE TITLE
(2.0.8) [ File Permission Bug ] Turning Suspend Function On

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#47]
While navigating to Settings ---> General ---> System ---> SUSPEND then click on suspend function which makes the button green which should mean it will be turning it on after hitting save.

i used the following data below.

Suspend services if payment overdue [X]
Suspend hold up limit: 6 
Late fee active: ON
Late fee invoice label: Late fee
Late fee price: 89
Late fee price type: currency 
Late fee taxable: [X]

Lets now hit  "SAVE" and see what happens.

Warning: file_put_contents(/usr/src/ucrm/app/cache/prod/../constants.php): failed to open stream: Permission denied in /usr/src/ucrm/src/AppBundle/Command/ConstantCommand.php on line 112
Redirecting to /settings/general/system/4/edit.

Then turning it off i get the same error.

Warning: file_put_contents(/usr/src/ucrm/app/cache/prod/../constants.php): failed to open stream: Permission denied in /usr/src/ucrm/src/AppBundle/Command/ConstantCommand.php on line 112
Redirecting to /settings/general/system/4/edit.

But then when redirected it says, Settings have been saved.

**Comment by UBNT-Petr** [comment]
We are looking into it. Thanks for reporting.

**Comment by Dstahl0** [comment]
Thanks for responding so fast @UBNT-Petr

**Comment by UBNT-Petr** [comment]
Until we release the bugfix, this workaround should help you: restart docker container using this:
`cd /home/ucrm
sudo docker-compose restart`

**Comment by Dstahl0** [comment]
@UBNT-Petr That seemed to fix it for now. Thanks

**Comment by UBNT-Petr** [comment]
fixed in v2.0.9
