### ISSUE TITLE
[ Request ] Librenms API Intergration

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#48]
Can we get librenms integrated into the client tab underneath the word billing? it would not be to hard to do as the form field can be under system settings and then the admin pastes the API URL and then once a admin or account user goes to a client page is echo's the username and thus uses curl to pull the bandwidth graph from librenms. This would also be nice for when clients login to there portal to also see what they been using over a period of time i.g 24 hours / 48 hours / 1 week / 1 month etc. This can all be called from librenms using api calls.

I have demonstrated the below graph ( Cacti ) for a example.

![screen shot 2016-07-22 at 8 48 15 pm](https://cloud.githubusercontent.com/assets/14851974/17074750/e33adf9a-504d-11e6-821b-54a1a84f3265.png)

![screen shot 2016-07-22 at 8 01 38 pm](https://cloud.githubusercontent.com/assets/14851974/17074266/cd61112c-5047-11e6-82f5-c69dabfc53f3.png)

![screen shot 2016-07-22 at 8 55 54 pm](https://cloud.githubusercontent.com/assets/14851974/17074792/03191db2-504f-11e6-857d-a7462930ed7e.png)

 @vlada-dev @UBNT-Petr

**Comment by Pakket** [comment]
Integration with Nagios, Cacti, Centreon, etc.. would be completely awesome!
+1 for this.

**Comment by Dstahl0** [comment]
Uploaded the client portal view.

**Comment by keksa** [comment]
We'll take a look into this, thanks for suggestion.

**Comment by UBNT-Petr** [comment]
As we decided to integrate UNMS into UCRM, we don't plan to add further "network management" tools directly into UCRM.

The integration will enable UCRM to show the basic network graphs and status while the more advanced views and stats will be available in UNMS. 

Read more here: https://community.ubnt.com/t5/UCRM-Complete-WISP-Management/UCRM-integration-with-UNMS/m-p/1919207#U1919207

Still, if you want some specific feature in UCRM, feel free to create a request here: https://community.ubnt.com/t5/UCRM-Feature-Requests/idb-p/UCRM-Ideas or refer to UNMS forum: https://community.ubnt.com/t5/UNMS-Next-Generation-Network/bd-p/UNMS-Alpha
