### ISSUE TITLE
[ Old PHP Version 7.0.8 ]

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#49]
The base install of the docker image has php version of ( 7.0.8 ) but there is now a version 7.0.9 which fixes some security vulnerabilities.

This is the image from the current docker image.

![screen shot 2016-07-26 at 1 48 22 am](https://cloud.githubusercontent.com/assets/14851974/17127366/1723f74c-52d3-11e6-97cd-a96de18e8346.png)

When will the php version be updated?
http://php.net/releases/7_0_9.php

**Comment by andreas4all** [comment]
It will be in next release.
