### ISSUE TITLE
[2.0.8]  Feedback url wrong.

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#50]
The URL on the dash board for " Tell us what you think on **our forum** "  is pointing to http://community.ubnt.com/t5/custom/page/page-id/Forums but it should be http://community.ubnt.com/t5/UCRM-Complete-WISP-Management/bd-p/UCRM

**Comment by UBNT-Petr** [comment]
yes it would be better, thanks

**Comment by Dstahl0** [comment]
Thanks @UBNT-Petr

**Comment by keksa** [comment]
fixed in 2.0.11
