### ISSUE TITLE
Update to 2.0.10 Does not Change Version number on home page.

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#51]
So after logging in after updating to 2.0.10 from 2.0.9 i am still being told via the web gui that i am running "you have 2.0.9". 

This is what the logs said from terminal during the update.

`dstahl@build-ucrm:/home/ucrm$ curl -fsSL https://raw.githubusercontent.com/U-CRM/billing/master/update.sh | sudo sh
[sudo] password for dstahl: 
Pulling postgresql (postgres:9.5)...
9.5: Pulling from library/postgres
Digest: sha256:e0a230a9f5b4e1b8b03bb3e8cf7322b0e42b7838c5c87f4545edb48f5eb8f077
Status: Image is up to date for postgres:9.5
Pulling crm_invoice_send_email_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
e110a4a17941: Already exists
d9f63633faf6: Already exists
ac309a5bc5d5: Already exists
4523ec888a62: Already exists
6a77f79ab9b5: Already exists
27243562b67c: Already exists
33e1803456c2: Already exists
a1219b0a1418: Already exists
5d70826c3bc6: Pull complete
a92e360c73b5: Pull complete
9438503c8d28: Pull complete
85176fd12cc4: Pull complete
0c5e83f3ccdc: Pull complete
b9d79555e8c0: Pull complete
82abfc3d5539: Pull complete
aab97bc126de: Pull complete
0e06547dd831: Pull complete
e262e70ab58c: Pull complete
d3fb5ddcc3cc: Extracting [============>                                      ] 6.554d3fb5ddcc3cc: Pull complete
43ca60ef0715: Pull complete
998a547ffdf8: Pull complete
837af765d74f: Pull complete
Digest: sha256:47fbb1af9ad906cb86d66c75d5c9d59950dadaa614451d35b82da3c4ec5578e2
Status: Downloaded newer image for ubnt/ucrm-billing:latest
Pulling elastic (elasticsearch:2)...
2: Pulling from library/elasticsearch
Digest: sha256:d866f6945a401e9486dc54c5242665692855ae58d4f0c42439925e9e5d9370ed
Status: Image is up to date for elasticsearch:2
Pulling crm_draft_approve_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
Digest: sha256:47fbb1af9ad906cb86d66c75d5c9d59950dadaa614451d35b82da3c4ec5578e2
Status: Image is up to date for ubnt/ucrm-billing:latest
Pulling web_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
Digest: sha256:47fbb1af9ad906cb86d66c75d5c9d59950dadaa614451d35b82da3c4ec5578e2
Status: Image is up to date for ubnt/ucrm-billing:latest
Pulling sync_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
Digest: sha256:47fbb1af9ad906cb86d66c75d5c9d59950dadaa614451d35b82da3c4ec5578e2
Status: Image is up to date for ubnt/ucrm-billing:latest
Stopping ucrm_web_app_1 ... done
Stopping ucrm_sync_app_1 ... done
Stopping ucrm_crm_draft_approve_app_1 ... done
Stopping ucrm_crm_invoice_send_email_app_1 ... done
Stopping ucrm_postgresql_1 ... done
Stopping ucrm_elastic_1 ... done
Starting ucrm_elastic_1
Starting ucrm_postgresql_1
Recreating ucrm_crm_draft_approve_app_1
Recreating ucrm_crm_invoice_send_email_app_1
Recreating ucrm_web_app_1
Recreating ucrm_sync_app_1`

So i have cleared my local web cache (Just incase) on canary latest build 54.0.28.11 64Bit ( Mac osx ) and no different in version numbers. i have also restarted the docker container as well with no luck. i am now going to do the update one more time to see if it does the trick. 

 Round 2 in updating the docker container. Terminal output below.

`dstahl@build-ucrm:/home/ucrm$ curl -fsSL https://raw.githubusercontent.com/U-CRM/billing/master/update.sh | sudo sh
Pulling postgresql (postgres:9.5)...
9.5: Pulling from library/postgres
Digest: sha256:e0a230a9f5b4e1b8b03bb3e8cf7322b0e42b7838c5c87f4545edb48f5eb8f077
Status: Image is up to date for postgres:9.5
Pulling crm_invoice_send_email_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
e110a4a17941: Already exists
d9f63633faf6: Already exists
ac309a5bc5d5: Already exists
4523ec888a62: Already exists
6a77f79ab9b5: Already exists
27243562b67c: Already exists
33e1803456c2: Already exists
a1219b0a1418: Already exists
66c40bfa7be6: Pull complete
5c2a44157e68: Pull complete
0c336910d807: Pull complete
4a51157d4679: Pull complete
fe69bbb9f782: Pull complete
80b4e2791231: Pull complete
0cae33ab5971: Pull complete
6afd1115003d: Pull complete
348bf50fffaa: Pull complete
02b7f902741b: Pull complete
c719bdddf7ac: Pull complete
42c906e15622: Pull complete
e136233dc742: Pull complete
5a6488e0ebe7: Pull complete
406d19c95b90: Pull complete
Digest: sha256:0d42b0e5857ce6cac302bc9e7af3ecac5fc135f5411d1a3b15d77646a099e99a
Status: Downloaded newer image for ubnt/ucrm-billing:latest
Pulling elastic (elasticsearch:2)...
2: Pulling from library/elasticsearch
Digest: sha256:d866f6945a401e9486dc54c5242665692855ae58d4f0c42439925e9e5d9370ed
Status: Image is up to date for elasticsearch:2
Pulling crm_draft_approve_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
Digest: sha256:0d42b0e5857ce6cac302bc9e7af3ecac5fc135f5411d1a3b15d77646a099e99a
Status: Image is up to date for ubnt/ucrm-billing:latest
Pulling web_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
Digest: sha256:0d42b0e5857ce6cac302bc9e7af3ecac5fc135f5411d1a3b15d77646a099e99a
Status: Image is up to date for ubnt/ucrm-billing:latest
Pulling sync_app (ubnt/ucrm-billing:latest)...
latest: Pulling from ubnt/ucrm-billing
Digest: sha256:0d42b0e5857ce6cac302bc9e7af3ecac5fc135f5411d1a3b15d77646a099e99a
Status: Image is up to date for ubnt/ucrm-billing:latest
Stopping ucrm_sync_app_1 ... done
Stopping ucrm_web_app_1 ... done
Stopping ucrm_crm_invoice_send_email_app_1 ... done
Stopping ucrm_crm_draft_approve_app_1 ... done
Stopping ucrm_postgresql_1 ... done
Stopping ucrm_elastic_1 ... done
Starting ucrm_elastic_1
Starting ucrm_postgresql_1
Recreating ucrm_web_app_1
Recreating ucrm_crm_invoice_send_email_app_1
Recreating ucrm_crm_draft_approve_app_1
Recreating ucrm_sync_app_1`

So After attempting the update process a second time, it now does in fact to be showing the proper version number. 

I Thought i just let everyone know just incase someone else has this issue.

**Comment by UBNT-Petr** [comment]
The version number is updated just after UCRM installation/update and then periodically. There were some github connection problems when we released v2.0.10 which might cause that. 
Thanks for reporting anyway.

**Comment by Dstahl0** [comment]
You're welcome @UBNT-Petr
