### ISSUE TITLE
Draft invoices don't approve

### ISSUE THREAD

**Issue by tobyrstephens** [U-CRM/billing#56]
After upgrading to 2.0.12, I am unable to approve draft invoices.  They are generated and I select either approve one-by-one or approve all, the system indicates they are queued for approval but they never receive the approved indication or an invoice number.

**Comment by keksa** [comment]
Hello @tobyrstephens, can you please try clicking the approve button on the draft detail page? That should approve the draft instantly without adding to queue. If an error happens, please post the content here.
Also, please post the contents of your docker-compose.yml file here. Thank you.

**Comment by tobyrstephens** [comment]
When I attempt to approve individual drafts, the following error occurs:

500 Internal Server Error

An error happened.

ZGVmNTAyMDA3ZTRhNDlmZjI5Mzg1YTllMWVmMDA5MTJkN2UwODRjOTI5YTU0Nzc4Yjg4MzNjMzNkNmQ2NDk2OGZhYjJlNzk5N2I3M2NhMDBkMTdhMjkxZWM1MGE2Y2U1MTMyMDhlMzljYzc4OTNmYmYxZjA2ZjUxNGU0MWRiNTJhMjc5NDNhODk1MDJiMzNjNTNiNzVkODQ3MjkwMTFmZmQwMjQxZjg0MDM2Y2IxZDY0M2RmMDE2ZGQwNDQzY2Y0ODI5ZDI1ZGQ5ZmRjNzc2ZGRlMzQzNzRlMWZkNGNmNWFhYzA5NDk5MGE3OTljYThkNTZjZDNhYjU4ZjFkYzI3NDg1OWIxMTFhMTgxMDcxZmE0NjU0MWE2ODJmNTFjZGNjOTA0NmJmZTBhYWYwNmI5NDcwMTE0ODQzOWIwMzA0MTRmYWJmZjc2YTcwMjBiYzE2MTM1YzU3ODI4OGJmOGYxNDY4ZGU3ZTRlMWI2ZWU1Yjc1ZTNlODM0MDUwYmUxNjA5MTY5ZThkMWJkYTE5ZTBjNzY0MGY0NThiNzRkOTk4NmFiNzZkNzljMjY2NTNkYWU2MWFjNTIxYTExNjM3OTUyNDZlZGQ2MmE0YTZmZjg3NDhmMWQyMTE1YzE2NWQ4OTAxODg0ZTQ5YWI0NGZjYTYzZjIzMjczODZkMDJhYzJmZDVlMzg0OWIyZjJhMzQxZDhlNDlkZjZmYjM5NmU0M2M2ZDk2ZmNkZmUwYzJiYzdmNTllODMwZjY5YTVhMjJiOGI4YjgwMjMyZjgwNDgzMjQ4NzU5MGM5YzYyMjQ4ZTkzNGExNWVmYzZlODNiNDRiMDgzZTIwODEzOTA5YTNhODcxYWE5NjdkNzY0NmU4MjNhODA4YTQxY2Y2YjVlODg0MzQyYmE0ZTYzMDNiNWQzOGU5NDA1YjcxYTE5MDQ2MjE5OTU5NTc1YTI4OGRiYWE0YTMzZjdkMzgwZTFmNTk3NGFiYQ==

**Comment by tobyrstephens** [comment]
version: '2'
services:
  postgresql:
    image: postgres:9.5
    restart: always
    env_file: docker-compose.env
    volumes:
      - /home/ucrm/postgres:/var/lib/postgresql/data

  web_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    links:
      - postgresql
      - elastic
    volumes:
      - /home/ucrm/data:/data
    ports:
      - 80:80
      - 81:81
      - 443:443
    command: "server"

  elastic:
    image: elasticsearch:2
    restart: always

  sync_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - /home/ucrm/data:/data
    links:
      - postgresql
    command: "sync"

  crm_invoice_send_email_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - /home/ucrm/data:/data
    links:
      - postgresql
    command: "crm_invoice_send_email"

  crm_draft_approve_app:
    image: ubnt/ucrm-billing:latest
    restart: always
    env_file: docker-compose.env
    volumes:
      - /home/ucrm/data:/data
    links:
      - postgresql
    command: "crm_draft_approve"

**Comment by tobyrstephens** [comment]
If it makes any difference, it doesn't seem that I'm able to create any invoice manually, either.

**Comment by keksa** [comment]
fixed in 2.0.13
