### ISSUE TITLE
Stripe subscriptions do not post payments

### ISSUE THREAD

**Issue by tobyrstephens** [U-CRM/billing#62]
Customers who subscribe to an invoice result in suspended status and late fees because payments aren't recorded within the application.

**Comment by keksa** [comment]
Hello @tobyrstephens, thanks for reporting this. I need a few information from you.

Did you set up webhook URL in your stripe dashboard correctly? (Account settings -> Webhooks) The webhook must be set up in live mode to work.

Do you see the subscription in stripe and does it have the payment? If so, there should be event log for webhooks there. Can you post the information from this log if there is an error?

**Comment by tobyrstephens** [comment]
That was the problem!  Thanks for your reply!  :o)

Toby R Stephens
Toby & Co
http://helpmetoby.com
417-934-6172
toby@helpmetoby.com


<http://call.phone.com/green/6ec82b14e6467e17befcc14fcb05f0f9>

--Only the mediocre are always at their best. -Jean Giraudoux --

--
Confidentiality Notice: This e-mail message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, use, disclosure, or
distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message.

**Comment by keksa** [comment]
@tobyrstephens So even if it was this in your case, we actually found an error in this and will be releasing hotfix shortly.

**Comment by UBNT-Petr** [comment]
Fixed in v. 2.0.14
