### ISSUE TITLE
Account Receivables Check Payment Method Received Issue Causing Suspended Service Email

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#63]
@UBNT-Petr @vlada-dev

 Just got a email from a customer also informing me his service was going to be temporally suspended, the customer paid via check and was entered into ucrm-billing.

![screen shot 2016-09-04 at 11 26 18 pm](https://cloud.githubusercontent.com/assets/14851974/18236751/af63acb6-72f7-11e6-9e44-8022a2aaa8cb.png)
![screen shot 2016-09-04 at 11 26 30 pm](https://cloud.githubusercontent.com/assets/14851974/18236754/b275b6ce-72f7-11e6-8c92-5a0f07e52d52.png)
^^ Note The date above.

Client name / Invoice Number / Sender / Recipient have been changed to protect their identity

![screen shot 2016-09-04 at 11 38 53 pm](https://cloud.githubusercontent.com/assets/14851974/18236855/ca2d673e-72f8-11e6-81f5-a7c654d114ce.png)

Thanks, 
David

**Comment by UBNT-Petr** [comment]
Can you please send me the invoice? I don't need customer details or item names.
But what would be helful are prices, taxes (percentage and value), discounts (percentage and value) per item and discount for whole invoice

Some other actions have been made to this invoice or payment? For example: any other payment created and deleted? Any refund created and deleted?

thanks.

**Comment by Dstahl0** [comment]
I will ask Sales tomorrow for this information.

**Comment by keksa** [comment]
Closing as problems with invoices being wrongly marked as partially paid were resolved in 2.1.2.
