### ISSUE TITLE
Client Name On suspended email is not showing.

### ISSUE THREAD

**Issue by Dstahl0** [U-CRM/billing#64]
@UBNT-Petr @vlada-dev 

The Client name is no showing up in the suspended email alert also there is a missing period at the end of suspended.

Notification Suspended Email code.
Dear %CLIENT_FIRST_NAME%! As we did not receive any payment for this service, it will be temporarily suspended

![screen shot 2016-09-04 at 11 47 13 pm](https://cloud.githubusercontent.com/assets/14851974/18236978/f5cc1fd8-72f9-11e6-8136-41240713db65.png)

**Comment by andreas4all** [comment]
Hi, thank you for your message.

Can you please check your client's first name, if it is correct or not contains any special characters?

Thank you.

**Comment by Dstahl0** [comment]
@andreas4all i just looked again, there is no special chars within the input field.

**Comment by keksa** [comment]
@Dstahl0 Are you still experiencing problems with this in latest version or was it fixed for you?

**Comment by Dstahl0** [comment]
So far everything is working. Closing report.
