### ISSUE TITLE
Suspended count not working on Dashboard

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#68]
I have several accounts that have been suspended automatically by the system (works good).  However, the "Suspended Service Count" on the dashboard says "0".

Also, it would be great to be able to view all suspended accounts, as I do not see a way to filter those in client view.

**Comment by keksa** [comment]
Hello @Pakket, we already have fix for this prepared and it will be in the next release.

The filter is really good suggestion, I'll take a look into that.

**Comment by keksa** [comment]
I can confirm there will be a way to filter clients with suspended services in the 2.1.0.
