### ISSUE TITLE
when BLOCKED USERS is on, when you make a payment it do not delete it on mikrotik

### ISSUE THREAD

**Issue by gustavo2147** [U-CRM/billing#69]
when a payment is on over due, the system make a BLOCKED USERS  on Firewall address list, but when i process the payment for that user the BLOCKED USERS  on Firewall address list, it is not deleted.

I always have to unblock the user manually.

![blocked users](https://cloud.githubusercontent.com/assets/22393941/18785238/0ccc6fca-8165-11e6-971b-082adb7ab119.jpg)

**Comment by Pakket** [comment]
I have the exact same problem.  This WAS working a couple of releases ago, however at some point, it broke.

**Comment by keksa** [comment]
Thank you for reporting this, we will take a look into it.

**Comment by keksa** [comment]
Confirmed, will be fixed in next release.

**Comment by Pakket** [comment]
I just want to clarify... I am having the same problem on EdgeMax ER-8.

**Comment by keksa** [comment]
@Pakket Yes, the problem was not with the actual sync script, but with not marking the device as unsynchronized after payment was accepted.
