### ISSUE TITLE
version 2.1 when i click on a client it give me an error 

### ISSUE THREAD

**Issue by gustavo2147** [U-CRM/billing#71]
![image](https://cloud.githubusercontent.com/assets/22393941/19016917/228bdc50-87f6-11e6-9fe1-fb1608b4a5da.png)

![image](https://cloud.githubusercontent.com/assets/22393941/19016912/fdc2442c-87f5-11e6-9b14-d1414477dab8.png)
![image](https://cloud.githubusercontent.com/assets/22393941/19016913/05048330-87f6-11e6-8d15-e2eb326fb85a.png)

**Comment by gustavo2147** [comment]
it give me the error that is on the image, it say: 500 internal server error

and the falowing code:

ZGVmNTAyMDBiOWQ1MTM3M2IyMGM2Nzc3ZDE1MTRlYzc4MDM3MjFjNzkyMTM2ZWRiZWUxZGY5OGU4YzA1ZDJmZjJlZTdhMWFiODU5ZDRkNTEyOTVjMmJlZjJjYjlkOTg0YzczZWJiMDM3MTQwMzY1YWY0MTE2YWZlMjk1ODdhYTI0ZDFkMmM1MDA0OTdjNzBiYzAwNDgyZWU1ZTdhNWEzZThhNDJkMzg4Yjk0NDU3MWMyZDE2MDViN2QwZmMxZDIxNmMyZTQ2M2UyNmY4MmRlMDEyYjU3MzcyNDUwMjA1OGEzYjA2ZTBlZjBmNmVhYWNmNTAzMGVmMDRmMTNmNTdlNDNjNGQ4M2JhMTBmM2E2ZmExYTFmOGYyNWY4YmZiMmNmZDZkNThhZGJjNDhlMjhiYjA0MDVlOGNjZjEwNWRkMGM3NjBhYWY5OTY0ZWMyNWZkMTMxNjg1YmRlNWVjN2FmYWFkOTViMWViNmRmYjVjM2Y0NGRhZGJkYTFlZDA3ZTg3YzgwNDc4NTRjZjUzYmQxOGMwOTJiNGQ0NzU2NzQ4MDdiYjBkY2I4MGE1MjEyMjYwM2M3MTFhZmJlOWY4MTI4ODg1NWNhOGUyMjVmMjcyMzg1NWYyNTQ0MTJjNmRkZTg2M2Y0NTAxNjZmNzRkN2E0ZjhkNDljOTliYzkzNGIyNGYxNWJmMGQ4ZDkwNmQ0MmRkMDYxYmQ4ZmRiNzFmOTc2MzQ1YmNhMDA3NzgyODE3ZGNkZGMyZmMxZmJjYTgxM2FmZGYxZDhmMjU2NzNhZTliYjAyM2FkMTNlMmZjYWViOGFkODQ5NDA5NDVkYjg5NzI5MzI4YTk4NjgwNTk3OWVjZDZhMjIzZjE2MmMwNjA5MmRkYWQ4NGFiYzVhZTNhNzJmMjJjZTMzMTViYzhlYjRmNzkw

**Comment by keksa** [comment]
Hello @gustavo2147, run the update script again please. We released a hotfix for this on friday night.
