### ISSUE TITLE
BUG: Invoice Numbers

### ISSUE THREAD

**Issue by thepagan** [U-CRM/billing#72]
Since 2.0.13 invoices no longer consecutively increase.  Issue still in 2.1.0

Changing init invoice number in settings changes the invoice number for all future generated invoices but it is the same for every invoice.

![screen shot 2016-10-03 at 10 19 00 am](https://cloud.githubusercontent.com/assets/1947126/19038755/61a11104-8953-11e6-8907-84093f27bdc6.png)

**Comment by UBNT-Petr** [comment]
will be fixed in the next release
