### ISSUE TITLE
2.1.0 suspension and CPE connectivity

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#73]
I added a new client and device today and noticed the changes in the service are as far as devices are concerned.  I do not believe that this is going to work with our setup (as mentioned in an earlier post).

Our CPE devices have a management VLAN and a service VLAN.  NO CONNECTIVITY USING THE NATIVE VLAN.

We have "no mangaement access" turned on, on the internet services VLAN, which blocks SSH and HTTP to the device from the internet interface.

All management traffic must come in on the management VLAN.  That said, I have no way to telling UCRM which interface (VLAN) to shut off, upon suspension.

I am afraid that if I give the UCRM the IP address of the management interface, that's the one it's going to shut down upon suspension.  If I give it the IP address of the internet interface, it will not be able to connect to it, as management is turned of on that interface.

I need to be able to provide both a Management interface and internet services interface to the UCRM.  That way, upon a suspension, the UCRM only shuts down the internet VLAN and remains connected via the Management VLAN, so that further actions can be performed.  This goes for traffic shaping as well.

**Comment by UBNT-Petr** [comment]
This is quite unusual configuration. I can imagine an enhancement for IPs of CPE - you will be able to specify which IP is for management (this will not be suspended) and which is used for client (this could be suspended)

However, the current implementation should work too. Both IPs will be suspended but this will not disable you to connect to CPE managment IP.

**Comment by Pakket** [comment]
I don't see why it's so unusual.  It seems like the most sensible way to keep the customer's CPE management interface from being accessible by the outside world.

Perhaps security is not as much of a concern to you as it is me, however, the ability to do so was made possible by the UBNT engineers, so I would have to assume that the concept was plausible to them as well.

**Comment by UBNT-Petr** [comment]
The "management IP" feature fixing this issue, has been introduced in UCRM v. 2.4.0-beta1. Will be available in 2.4.0 stable version by the end of this month.
