### ISSUE TITLE
Two clients showing partial payments when payment was in full

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#74]
I have two clients that are showing as having partial payments for last month, when the payments were in full.  The UCRM keeps suspending them, but they are caught up.

![partial-1](https://cloud.githubusercontent.com/assets/19694329/19153622/56621bae-8ba5-11e6-99e7-ad2a1aff490f.PNG)

![partial-2](https://cloud.githubusercontent.com/assets/19694329/19153628/59e68418-8ba5-11e6-8e11-7336eaf11548.PNG)

**Comment by Pakket** [comment]
Update:  I have tried deleting the payment and re-applying it and the invoice still reflects "Partial", even thought he full amount was applied.

**Comment by keksa** [comment]
Thanks for reporting this, I think it's some kind of rounding error, we'll take a look into this.

**Comment by keksa** [comment]
We will be releasing hotfix for this soon. You will need to reapply the payments for changes to take effect.

**Comment by keksa** [comment]
2.1.2 has been released, please try unmatching the payments and matching them back, should help

**Comment by Pakket** [comment]
Keksa!
I am trying to unmatch and rematch the payments, as the ones marked partial are causing my clients to get suspended.  When I try to match the payments, I am getting a 500 Server error.  I have rebooted the server and still get the error.

This is becoming a nightmare and causing my clients to be angry.  Can you please help with this?  if I need to, I can send you a copy of the VHD so you can view what's going on.

![match payments](https://cloud.githubusercontent.com/assets/19694329/19440928/c9bc6e42-9451-11e6-8d8c-a465571711aa.PNG)

**Comment by keksa** [comment]
Fixed in 2.1.3.
