### ISSUE TITLE
Bug: Unmatched payments either reporting incorrectly or not showing up

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#75]
When viewing our Dashboard, it tells us that we have unmatched payments.  Clicking on the link brings us to a page that yields no results.  I am not sure if the system is reporting it incorrectly OR if we actually have unmatched payments and they aren't showing.

![unmatched-1](https://cloud.githubusercontent.com/assets/19694329/19239783/9cc43978-8ed5-11e6-9bd5-654a9d286507.PNG)
![unmatched-2](https://cloud.githubusercontent.com/assets/19694329/19239782/9cc3567a-8ed5-11e6-9e47-a9985a9d7981.PNG)

**Comment by keksa** [comment]
Hello @Pakket, could you send me latest database backup file from Settings -> Tools -> Database backup? (Preferably to my email.)

**Comment by Pakket** [comment]
Sent via email.

**Comment by keksa** [comment]
@Pakket This is reported incorrectly, you have no unmatched payments. The payment being reported on dashboard belongs to archived client and the query used for unmatched payments count takes him as not existing, thus reporting the payment as unmatched.
The unmatched payment list works correctly.

**Comment by keksa** [comment]
Should be fixed in 2.1.3.
