### ISSUE TITLE
KES missing from Currency List. 

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#79]
Latest Beta misses Kenya Shillings (KES / Ksh) from the list of currencies.

**Comment by keksa** [comment]
Hello @arebacollins, they will be added in next release.

**Comment by arebacollins** [comment]
Thanks for adding the currency, there is a tiny formatting issue. 
 Current display: KES123453
Correct format: Ksh 123455 . 

A space would help in the meantime , so that display is modified from  KES500 to "KES 500" or "Ksh 500"

**Comment by keksa** [comment]
@arebacollins Yes, this is a known problem, we are using internationalization library built into our programming language and it seems it has support for very few currencies correctly. We will be looking into this together with translations, but for now it's low priority.

**Comment by arebacollins** [comment]
Fair enough.
