### ISSUE TITLE
Suspend feature requiring manual action

### ISSUE THREAD

**Issue by tobyrstephens** [U-CRM/billing#82]
Since 2.1.0 I have had to turn off then on the suspend feature in the hardware device to get the suspend rules to sync.  No action is taken to add the client IP to the blocked users list until I have turned suspend off, then on, on the network device edit page (and save in between changes).

Thanks!

**Comment by keksa** [comment]
Hello @tobyrstephens we fixed couple of bugs around this in 2.1.3 and 2.1.4, what version are you running?

**Comment by tobyrstephens** [comment]
I am updated to 2.1.4
Thanks

**Comment by keksa** [comment]
Ok, we'll take a look into it.

**Comment by UBNT-Petr** [comment]
This bug should be fixed now.
