### ISSUE TITLE
Pre Invoice (quotation?)

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#83]
(Apologies if its a dupe)
Is it possible to have an initial state / draft stage for invoices thats got a separate pdf template to enable send quotations to clients prior to buying? 

Implementation basically a "state" drop down that makes a quote => invoice transition, and basically same forms for both invoice and quote with difference in output presentation of the PDF.

**Comment by keksa** [comment]
Hello @arebacollins we already have invoice quotes in our features wishlist, so it will be implemented some time in the future. Can't say when though. Thanks for the feedback.

**Comment by arebacollins** [comment]
An easy workaround for now might be an ability to create multiple pdf templates, so you have a generate pdf as a quote or email attachment as quote.

**Comment by arebacollins** [comment]
see draft invoices on the left hand menu. I dont see much it does as creating a draft invoice creates an invoice anyway. Might this be a placeholder for this functionality? and would it make sense to just name it Quotes instead of Draft invoices (at least since invoices can be created and saved (a pseudo draft state).

**Comment by keksa** [comment]
@arebacollins We have quotes in wishlist. Drafts are something else altogether. Some users don't want the invoice drafts to be approved automatically, so when a invoice draft from recurring service is created it is shown in this section. Before 2.1.9 they were mixed with invoices.

**Comment by zipcodetechnology** [comment]
+1
