### ISSUE TITLE
PDF / Email statement

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#88]
Would be good to be able to send a copy of a client's statement in summary form (just like it shows on the statement page of the billing tab" via email and downloadable via pdf.

**Comment by UBNT-Petr** [comment]
Added to wishlist. In the near future, we will focus more on client's statement and exports, as well as exports to some accounting softwares.

**Comment by arebacollins** [comment]
A couple of filters (date to, date from), an automatic send statement every xxx days on the user under billing tab, and possibly an ability to send the statement as an CSV would be awesome.

**Comment by arebacollins** [comment]
Awesome! I can live without "email statement" for now as the summary, filters and table view are all there. 

Customizing the pdf outout would be a great add to this.
