### ISSUE TITLE
Ad Pay Invoice inside Invoice view page

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#89]
With the Invoice open, would be helpful to have a "Pay Invoice" or "Make Payment" button to open payments form with dates, and invoice pre selected so one can enter amount and submit. This would then refresh the open invoice with the "Paid" change.

**Comment by keksa** [comment]
Hello @arebacollins, thanks for the suggestion. We are now making all sorts of UI/UX improvements, I think this can be easily included with that.
