### ISSUE TITLE
When editing Customer Info, clicking on <back returns to clients list instead of client page.

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#91]
I don't know if this is by design, but the general question is: when editing customer A, and you chose not to continue and click on the back button, would it not make sense to go back to the client details page as opposed to going to the clients list?

**Comment by arebacollins** [comment]
Same UI issues affecting payments, when you delete a payment it takes you back to payments list, not the client account where you are trying to delete.

**Comment by keksa** [comment]
Hello @arebacollins, we are actually removing the "back button", instead there will be something like "Clients / John Doe / Edit" in page header and if you click "Clients" in there you will go to clients list, if you click "John Doe" you will go to the client detail.

**Comment by arebacollins** [comment]
Excellent, this solves the issues I am having with the other stuff as well.

**Comment by keksa** [comment]
Done in 2.1.9.
