### ISSUE TITLE
Payment Option : select multiple invoices

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#92]
Hello, 
I have a scenario, where payments need to be made for more than one invoice, and sometimes this needs to be manually specified. Is there a way to add this option in Payments, so that instead of just selecting one invoice, and the rest remaining hanging, one can specify multiple invoices?

**Comment by keksa** [comment]
Hello @arebacollins, not in the current release, but we have this feature almost ready. Should be in one of the next releases.

**Comment by keksa** [comment]
Done in 2.1.9.
