### ISSUE TITLE
Late fees

### ISSUE THREAD

**Issue by Pakket** [U-CRM/billing#93]
Guys, I am still having a problem with the system charging late fees right when the invoice is created.  I have looked and looked and cannot for the life of me figure out why it is doing this.  Can I get one of you to log in to my system and take a look?  i have an account set up for Ondra.  if you need the login info again, I can email it to you.

Thank you so much!

**Comment by UBNT-Petr** [comment]
Please, send me some example. From what I can see, all late fees were created correctly.

Also check these parameters which are applied:
- Suspend hold up limit (in settings > general > system > suspend)
- Invoice maturity days (in organization and client settings)

Late fee is generated on: Invoice create day + maturity days + suspend hold up limit
