### ISSUE TITLE
Email Queue. Allow to limit number of emails system can send at a given time.

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#94]
I am getting lots of blocked messages from zoho with the warning, "exceeded mail limit". I think it would be nice to be able to configure mailer to only be able to send a given number of emails at any given time regardless of the frequence of "send invoice" or "send receipt" clicking. 

Regards, 
Collins.

**Comment by UBNT-Petr** [comment]
Antiflood and Throttler settings for UCRM mailer will be introduced in the upcoming version 2.5.0
