### ISSUE TITLE
Bulk update of Invoice Drafts throws Error 500

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#97]
When you select all, and click on bulk update draft Invoices, System approves the first item on the list and throws an error 500.

**Comment by keksa** [comment]
Hello @arebacollins, we found a bug with invoice number generator, that will be fixed in next release. That's the only bug I see reported in our bug tracker about invoicing. However, could you please post the error message it gives you next time you see an 500 error?

**Comment by arebacollins** [comment]
I submitted the error message on the form that came on. Will post it here if it'll be helpful.

**Comment by keksa** [comment]
@arebacollins In that case it should be the one we got. No need to post.

**Comment by keksa** [comment]
Fixed in 2.1.10.
