### ISSUE TITLE
A question / suggestion on the "use credit" feature.

### ISSUE THREAD

**Issue by arebacollins** [U-CRM/billing#99]
Is there a method as to how the "use credit" feature debits the credit account? I ask because I have noticed it is not in order, and Im wondering if I am missing something. Here is an example. 

John Doe's Invoices.
Invoice XYZ001: Jan 1st 10,000 Ksh. 
Invoice XYZ002:  Feb 1st 15,000 Ksh.
Invoice XYZ 003: March 1st. 18,000 Ksh. 

John Does Payments. 
Payment 5th Jan Ksh 15,000 
Payment 18th Jan. Ksh 20,000 
Payment March 2nd Ksh 10,000

What the system did. 
5th of Jan, added 5,000 to the credit account. 
18th Jan, added 20,000 to the credit account.  (total 25,000 in the credit account).
1st Feb: Automatically paid from credit the Invoice XYZ002. ******** (Credit Balance is 10,000)
March 1st: Automatically paid partially from credit account to XYZ003: Invoice partially paid, balance on Invoice Ksh 8000. 
March 2nd: Invoice XYZ003 fully paid from and credit topped up to Ksh 2000. 

The Math works, eventually the figure at the end of the day is accurate, and so client account status will not be affected. However, the problem is with the way this credit is applied, and the invoices that show on the payment (and consequently the payments that show up on the invoice). Is it possible to adjust, so that a rule of First-in-First-out is applied to credit, so that first credit's payment ID is consumed first and shows up first on the Invoice. I noticed some randomization of this and would recommend a config feature under accounts, that would give the choice of First in First out, or using Credits that cover a full invoice first then piecing bits and pieces together. 

I can draw if clarification is needed.

**Comment by UBNT-Petr** [comment]
As of v. 2.1.10 the overpayments in the client's credit are used in proper order, from oldest to newest. Thanks for reporting.
